### ISSUE TITLE
Practica 6

### ISSUE THREAD

**Issue by Heidi-19** [SistemasTecTlaxiaco/practica-de-hilos-Heidi-19#2]
[Practica 6 - Heidi Lucy Bautista Sanjuan 4US.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-Heidi-19/files/8436534/Practica.6.-.Heidi.Lucy.Bautista.Sanjuan.4US.pdf)

**Comment by JudithReynaCS** [comment]
CALIFICACION:17.4%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
